local LSM = LibStub("LibSharedMedia-3.0")

LSM:Register("background","ElvUI Blank", [[Interface\BUTTONS\WHITE8X8]])
LSM:Register("border", "ElvUI GlowBorder", [[Interface\AddOns\ElvUI\media\textures\glowTex.tga]])
LSM:Register("font", "Oswald Regular", [[Interface\AddOns\ElvUI\media\fonts\Oswald-Regular.ttf]])
LSM:Register("font", "AgencyFB Bold", [[Interface\AddOns\ElvUI\media\fonts\AgencyFB_Bold.ttf]])
LSM:Register("font", "HOOGE (xCT)", [[Interface\AddOns\ElvUI\media\fonts\HOOGE.TTF]])
LSM:Register("font", "Oswald Light", [[Interface\AddOns\ElvUI\media\fonts\Oswald-Light.ttf]])
LSM:Register("font", "FrizQT", [[Interface\AddOns\ElvUI\media\fonts\FrizQT.ttf]])
LSM:Register("font", "Oswald Bold", [[Interface\AddOns\ElvUI\media\fonts\Oswald-Bold.ttf]])
LSM:Register("font", "BigNoodleTitling", [[Interface\AddOns\ElvUI\media\fonts\BigNoodleTitling.ttf]])
LSM:Register("font", "ElvUI Alt-Font", [[Interface\AddOns\ElvUI\media\fonts\Continuum_Medium.ttf]])
LSM:Register("font","ElvUI Alt-Combat", [[Interface\AddOns\ElvUI\media\fonts\DieDieDie.ttf]])
LSM:Register("font","ElvUI Combat", [[Interface\AddOns\ElvUI\media\fonts\Action_Man.ttf]])
LSM:Register("font","ElvUI Font", [[Interface\AddOns\ElvUI\media\fonts\PT_Sans_Narrow.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "ElvUI Pixel", [[Interface\AddOns\ElvUI\media\fonts\Homespun.ttf]],LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("sound","Warning", [[Interface\AddOns\ElvUI\media\sounds\warning.mp3]])
LSM:Register("sound","Whisper Alert", [[Interface\AddOns\ElvUI\media\sounds\whisper.mp3]])
LSM:Register("statusbar","Normal", [[Interface\AddOns\ElvUI\media\textures\Normal.tga]])
LSM:Register("statusbar","ElvUI Gloss", [[Interface\AddOns\ElvUI\media\textures\normTex.tga]])
LSM:Register("statusbar","ElvUI Norm", [[Interface\AddOns\ElvUI\media\textures\normTex2.tga]])
LSM:Register("statusbar","Minimalist", [[Interface\AddOns\ElvUI\media\textures\Minimalist.tga]])
LSM:Register("statusbar","Flatt", [[Interface\AddOns\ElvUI\media\textures\flatt.tga]])

