local E, L, C = unpack(select(2, ...))

--[[
["profileKeys"] = {
    [UnitName("player").." - "..GetRealmName()] = "Default",
  },
["profiles"] = {
		["Default"] = {
    
  },
]]

local name, ace3 = "xCTSavedDB", true
local profile = {
  ["megaDamage"] = {
    ["enableMegaDamage"] = true,
  },
  ["spells"] = {
    ["items"] = {
      ["Weapon"] = {
        ["Two-Handed Maces"] = false,
        ["One-Handed Swords"] = false,
        ["Staves"] = false,
        ["Crossbows"] = false,
        ["Polearms"] = false,
        ["One-Handed Maces"] = false,
        ["Fishing Poles"] = false,
        ["Two-Handed Swords"] = false,
        ["Miscellaneous"] = false,
        ["Bows"] = false,
        ["One-Handed Axes"] = false,
        ["Guns"] = false,
        ["Fist Weapons"] = false,
        ["Daggers"] = false,
        ["Wands"] = false,
        ["Thrown"] = false,
        ["Two-Handed Axes"] = false,
      },
      ["Glyph"] = {
        ["Warrior"] = false,
        ["Paladin"] = false,
        ["Shaman"] = false,
        ["Monk"] = false,
        ["Rogue"] = false,
        ["Mage"] = false,
        ["Warlock"] = false,
        ["Priest"] = false,
        ["Hunter"] = false,
        ["Death Knight"] = false,
        ["Druid"] = false,
      },
      ["Trade Goods"] = {
        ["Other"] = false,
        ["Elemental"] = false,
        ["Jewelcrafting"] = false,
        ["Herb"] = false,
        ["Enchanting"] = false,
        ["Devices"] = false,
        ["Cooking"] = false,
        ["Explosives"] = false,
        ["Materials"] = false,
        ["Cloth"] = false,
        ["Item Enchantment"] = false,
        ["Leather"] = false,
        ["Metal & Stone"] = false,
        ["Parts"] = false,
      },
      ["Miscellaneous"] = {
        ["Other"] = false,
        ["Reagent"] = false,
        ["Companion Pets"] = false,
        ["Junk"] = false,
        ["Holiday"] = false,
        ["Mount"] = false,
      },
      ["Recipe"] = {
        ["Inscription"] = false,
        ["Blacksmithing"] = false,
        ["Alchemy"] = false,
        ["First Aid"] = false,
        ["Book"] = false,
        ["Cooking"] = false,
        ["Jewelcrafting"] = false,
        ["Fishing"] = false,
        ["Engineering"] = false,
        ["Leatherworking"] = false,
        ["Tailoring"] = false,
        ["Enchanting"] = false,
      },
      ["Consumable"] = {
        ["Other"] = false,
        ["Elixir"] = false,
        ["Item Enhancement"] = false,
        ["Potion"] = false,
        ["Scroll"] = false,
        ["Flask"] = false,
        ["Bandage"] = false,
        ["Food & Drink"] = false,
      },
      ["version"] = 1,
      ["Gem"] = {
        ["Simple"] = false,
        ["Blue"] = false,
        ["Meta"] = false,
        ["Cogwheel"] = false,
        ["Purple"] = false,
        ["Green"] = false,
        ["Prismatic"] = false,
        ["Yellow"] = false,
        ["Orange"] = false,
        ["Red"] = false,
      },
      ["Battle Pets"] = {
        ["Dragonkin"] = false,
        ["Humanoid"] = false,
        ["Elemental"] = false,
        ["Critter"] = false,
        ["Magic"] = false,
        ["Flying"] = false,
        ["Aquatic"] = false,
        ["Undead"] = false,
        ["Beast"] = false,
        ["Mechanical"] = false,
      },
      ["Armor"] = {
        ["Leather"] = false,
        ["Shields"] = false,
        ["Mail"] = false,
        ["Plate"] = false,
        ["Cloth"] = false,
        ["Miscellaneous"] = false,
      },
      ["Quest"] = {
        ["Quest"] = false,
      },
      ["Container"] = {
        ["Bag"] = false,
        ["Mining Bag"] = false,
        ["Cooking Bag"] = false,
        ["Gem Bag"] = false,
        ["Tackle Box"] = false,
        ["Engineering Bag"] = false,
        ["Herb Bag"] = false,
        ["Leatherworking Bag"] = false,
        ["Inscription Bag"] = false,
        ["Enchanting Bag"] = false,
      },
    },
    ["mergeCriticalsByThemselves"] = true,
    ["mergeDontMergeCriticals"] = false,
  },
  ["blizzardFCT"] = {
    ["font"] = "Oswald Regular",
  },
  ["frames"] = {
    ["general"] = {
      ["fontSize"] = 15,
      ["font"] = "Oswald Regular",
      ["fontOutline"] = "2OUTLINE",
    },
    ["power"] = {
      ["enabledFrame"] = false,
      ["font"] = "Oswald Regular",
      ["fontOutline"] = "2OUTLINE",
    },
    ["healing"] = {
      ["fontSize"] = 15,
      ["fontOutline"] = "2OUTLINE",
      ["font"] = "Oswald Regular",
    },
    ["outgoing"] = {
      ["fontSize"] = 15,
      ["font"] = "Oswald Regular",
      ["fontOutline"] = "2OUTLINE",
    },
    ["critical"] = {
      ["fontSize"] = 20,
      ["font"] = "Oswald Regular",
      ["fontOutline"] = "2OUTLINE",
    },
    ["procs"] = {
      ["fontSize"] = 25,
      ["fontOutline"] = "2OUTLINE",
      ["font"] = "Oswald Regular",
    },
    ["loot"] = {
      ["enabledFrame"] = false,
      ["fontOutline"] = "2OUTLINE",
      ["font"] = "Oswald Regular",
    },
    ["class"] = {
      ["enabledFrame"] = false,
      ["font"] = "Oswald Regular",
      ["fontOutline"] = "2OUTLINE",
    },
    ["damage"] = {
      ["fontSize"] = 15,
      ["fontOutline"] = "2OUTLINE",
      ["font"] = "Oswald Regular",
    },
  },
  ["showStartupText"] = false,
}

E:RegisterProfile(name, profile, ace3)
